### ISSUE TITLE
::Fixnum is deprecated in Ruby 2.4

### ISSUE THREAD

**Issue by ddarbyson** [jqr/php-serialize#16]
Ran into this today:

`/home/username/.gem/ruby/2.4/gems/php-serialize-1.2.0/lib/php_serialize.rb:64: warning: constant ::Fixnum is deprecated`

Nice gem btw!

**Comment by jqr** [comment]
Yeah, Ruby 2.4 [unified Fixnum and Bignum into just Integer](https://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html).

I'm not using this gem any more but this should be an easy fix for someone who's eager to help.

**Comment by zdenkers** [comment]
looks like someone fixed this issue back in 2017 but the gem never got updated. any chance you could update the gem with the latest?

**Comment by jqr** [comment]
Yep, working on that now.

**Comment by jqr** [comment]
Merged https://github.com/jqr/php-serialize/pull/17 and [Released as 1.3.0](https://rubygems.org/gems/php-serialize/versions/1.3.0).
