### ISSUE TITLE
Release gem

### ISSUE THREAD

**Issue by jqr** [jqr/php-serialize#9]

**Comment by ivanovaleksey** [comment]
Hi @jqr, 

any updates on this?

**Comment by jqr** [comment]
No from the original maintainer. Thanks for the reminder.

I'll push this out to a new gem instead. Give me a little bit of time :)

**Comment by jqr** [comment]
Trying one more time with the author, but I've got a refreshed version nearing release in the [modernize branch](https://github.com/jqr/php-serialize/tree/modernize).

If I have to use a new gem name, what do you think about php-serializer. Rationale: I hate numbers in gem names.

**Comment by jqr** [comment]
Yay, both the original author and myself now have access to push gems. I've released the master branch as [version 1.2.0](https://github.com/jqr/php-serialize/blob/master/CHANGELOG.md#120-2017-06-29).

**Comment by ivanovaleksey** [comment]
awesome! thanks @jqr
